services:
  - type: web
    name: medical-bot-backend
    env: node
    branch: master
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    instanceType: free
    autoDeploy: true
